---
- op: replace
  path: /spec/template/spec/source/repoURL
  value: https://github.com/mike-kingsbury/infra-deployments.git
- op: replace
  path: /spec/template/spec/source/targetRevision
  value: preview-test-grafana
