---
apiVersion: observability.openshift.io/v1
kind: ClusterLogForwarder
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "1"
  name: instance
spec:
  collector:
    resources:
      limits: {}
      requests: {}
    nodeSelector: {}
    tolerations: {}
  outputs:
    - name: splunk-receiver-application
      type: splunk
      splunk:
        url: https://http-inputs-rhcorporate.splunkcloud.com
        authentication:
          token: log-forwarder-splunk-rhtap-application-secret
    - name: splunk-receiver-audit
      type: splunk
      splunk:
        url: https://http-inputs-rhcorporate.splunkcloud.com
        authentication:
          token: log-forwarder-splunk-rhtap-audit-secret
  filters:
    - name: parse-json
      type: parse
  pipelines:
    - name: fluentd-forward-logs-to-splunk-rhtap-app-index
      inputRefs:
        - application
      outputRefs:
        - splunk-receiver-application
      filterRefs:
        - parse-json
    - name: fluentd-forward-logs-to-splunk-rhtap-audit-index
      inputRefs:
        - infrastructure
        - audit
      outputRefs:
        - splunk-receiver-audit
      filterRefs:
        - parse-json
  serviceAccount:
    name: log-collector