apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: tracing-workload-otel-collector
  labels:
    ### Prevent the repoURL from being transformed to a local fork name.
    noSourceTransform: "true"
spec:
  generators:
    - merge:
        mergeKeys:
          - nameNormalized
        generators:
          - clusters:
              values:
                sourceRoot: components/tracing/otel-collector
                environment: staging
                clusterDir: ""
          - list:
              elements: []
  template:
    metadata:
      name: tracing-workload-otel-collector-{{nameNormalized}}
    spec:
      project: default
      sources:
          # Chart from the OTel Project
        - chart: opentelemetry-collector
          path: '{{values.sourceRoot}}/{{values.environment}}/{{values.clusterDir}}'
          repoURL: https://open-telemetry.github.io/opentelemetry-helm-charts
          targetRevision: 0.90.1
          helm:
            parameters:
              - name: "image.repository"
                value: otel/opentelemetry-collector-k8s
              - name: "mode"
                value: deployment
            valueFiles:
            - $values/components/tracing/otel-collector/{{values.environment}}/otel-collector-helm-values.yaml
          # Values for chart from git
        - repoURL: https://github.com/mike-kingsbury/infra-deployments.git
          targetRevision: preview-tracing
          ref: values
      destination:
        namespace: konflux-otel
        server: '{{server}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
        retry:
          limit: 50
          backoff:
            duration: 10s
            factor: 2
            maxDuration: 3m
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: enable-tekton-tracing
spec:
  generators:
    - merge:
        mergeKeys:
          - nameNormalized
        generators:
          - clusters:
              values:
                sourceRoot: configs/enable-tekton-tracing
                environment: staging
                clusterDir: ""
          - list:
              elements: []
  template:
    metadata:
      name: enable-tekton-tracing-{{nameNormalized}}
    spec:
      project: default
      source:
        path: configs/enable-tekton-tracing
        repoURL: https://github.com/redhat-appstudio/infra-deployments.git
        targetRevision: main
      destination:
        server: '{{server}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        retry:
          limit: -1
          backoff:
            duration: 10s
            factor: 2
            maxDuration: 3m